### ISSUE TITLE
question： why there is no reducer to handle INDEX_NAV, did i miss anything?

### ISSUE THREAD

**Issue by zjufish** [grommet/grommet-ferret#13]
greped reducers directory and got nothing there. :(

**Comment by alansouzati** [comment]
Thanks for reporting this, if you look at the action we are using the history api to manage state.

https://github.com/grommet/grommet-ferret/blob/2628df0c57d314e127928647a8e43006e59f0036/src/js/actions.js#L193

That's why we don't have a reducer. Let us know if you have a different approach for that.
